report a newer version of ASM compatability
The old code would blow up parsing newer classes.  Update the library to
ASM9 and report ASM9 compatability to avoid exceptions like:

```
java.lang.UnsupportedOperationException: Module requires ASM6
        at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:145)
        at org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:758)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:557)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at org.jenkinsci.deprecatedusage.DeprecatedUsage.analyze(DeprecatedUsage.java:108)
        at org.jenkinsci.deprecatedusage.DeprecatedUsage.analyzeWithClassVisitor(DeprecatedUsage.java:62)
        at org.jenkinsci.deprecatedusage.DeprecatedUsage.analyze(DeprecatedUsage.java:51)
        at org.jenkinsci.deprecatedusage.Main.lambda$3(Main.java:152)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
java.lang.UnsupportedOperationException: NestHost requires ASM7..
.        at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:165)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:563)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at org.jenkinsci.deprecatedusage.DeprecatedUsage.analyze(DeprecatedUsage.java:108)
        at org.jenkinsci.deprecatedusage.DeprecatedUsage.analyzeWithClassVisitor(DeprecatedUsage.java:62)
        at org.jenkinsci.deprecatedusage.DeprecatedUsage.analyze(DeprecatedUsage.java:51)
        at org.jenkinsci.deprecatedusage.Main.lambda$3(Main.java:152)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```